sudo: false
language: go
jobs:
  include:
    - stage: test
      install:
        - go get github.com/golang/lint/golint
        - go get github.com/golang/dep/cmd/dep
      before_script:
        - dep ensure
      script:
        - golint   -set_exit_status $(go list ./... | grep -v /vendor/)
        - go vet   -v               $(go list ./... | grep -v /vendor/)
        - go build -v               $(go list ./... | grep -v /vendor/)
        - go test  -v -race         $(go list ./... | grep -v /vendor/)
        # extensive testing and code coverage
        - |
            echo "" > coverage.txt
            for FNAME in $(go list ./... | grep -v vendor); do
              go test -race -coverprofile=profile.out -covermode=atomic ${FNAME}
              if [ -f profile.out ]; then
                cat profile.out >> coverage.txt
                rm profile.out
              fi
            done
      after_success:
        - bash <(curl -s https://codecov.io/bash)
